name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # --- Node.js setup ---
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # --- Install dependencies in web folder ---
    - name: Install Node dependencies
      working-directory: ./web
      run: npm install

    # --- Build React project ---
    - name: Build
      working-directory: ./web
      run: npm run build